"""Initial migration.

Revision ID: 413866b65ab1
Revises: 
Create Date: 2024-07-05 12:48:12.020955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413866b65ab1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('groupID')
    )
    op.create_table('user',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='user_role'), nullable=False),
    sa.Column('groupID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groupID'], ['group.groupID'], ),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('login')
    )
    op.create_table('prompt',
    sa.Column('promptID', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('promptID')
    )
    op.create_table('note',
    sa.Column('noteID', sa.Integer(), nullable=False),
    sa.Column('note_value', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.promptID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('noteID')
    )
    op.create_table('vote',
    sa.Column('voteID', sa.Integer(), nullable=False),
    sa.Column('vote_value', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.promptID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('voteID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('note')
    op.drop_table('prompt')
    op.drop_table('user')
    op.drop_table('group')
    # ### end Alembic commands ###
